# Generated by Django 5.2.8 on 2025-12-10 15:34

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نوع الغسيل')),
                ('name_ar', models.CharField(max_length=100, null=True, verbose_name='نوع الغسيل')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='نوع الغسيل')),
                ('name_fr', models.CharField(max_length=100, null=True, verbose_name='نوع الغسيل')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='سعر الزبون')),
                ('worker_commission', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='أجر العامل')),
                ('icon', models.CharField(default='🚗', max_length=50, verbose_name='أيقونة الخدمة')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': '1. قائمة الخدمات 📋',
            },
        ),
        migrations.CreateModel(
            name='StationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_mode', models.CharField(choices=[('commission', '📊 نظام العمولة (Mode 1)'), ('salary', '💼 نظام الرواتب الثابتة (Mode 2)')], default='commission', max_length=20, verbose_name='نظام العمل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': '⚙️ إعدادات النظام',
                'verbose_name_plural': '⚙️ إعدادات النظام (التبديل)',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
            ],
            options={
                'verbose_name': '💰 تقرير الرواتب',
                'verbose_name_plural': '💰 تقارير الرواتب',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkerProxy',
            fields=[
            ],
            options={
                'verbose_name': 'إضافة عامل',
                'verbose_name_plural': '3. فريق العمل 👷',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='قيمة المصروف (د.ج)')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='ملاحظة / سبب')),
                ('worker', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='العامل')),
            ],
            options={
                'verbose_name': 'خصم / سلفة',
                'verbose_name_plural': '4. سجل المصروفات والسلف 💸',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default='زبون مباشر', max_length=100, verbose_name='اسم الزبون')),
                ('phone', models.CharField(default='-', max_length=15, verbose_name='رقم الهاتف')),
                ('car_plate', models.CharField(default='بدون لوحة', max_length=20, verbose_name='لوحة السيارة')),
                ('source', models.CharField(choices=[('website', '🌍 حجز من الموقع'), ('manual', '👋 زبون مباشر (كاشير)')], default='manual', max_length=10, verbose_name='المصدر')),
                ('car_type', models.CharField(default='غير محدد', max_length=50, verbose_name='نوع السيارة')),
                ('voice_audio', models.FileField(blank=True, null=True, upload_to='voice_notes/%Y/%m/', verbose_name='تسجيل صوتي 🎙️')),
                ('custom_desc', models.TextField(blank=True, null=True, verbose_name='وصف المشكلة/الطلب')),
                ('status', models.CharField(choices=[('pending', '⏳ قيد الانتظار'), ('processing', '🧼 جاري العمل'), ('completed', '✅ مكتملة'), ('canceled', '❌ ملغاة')], default='processing', max_length=15, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت التسجيل')),
                ('final_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8, verbose_name='السعر النهائي')),
                ('final_commission', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8, verbose_name='عمولة العامل')),
                ('worker', models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='👨\u200d🔧 العامل المنفذ')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.service', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'عملية',
                'verbose_name_plural': '2. سجل العمليات (الكاشير) 🚘',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
            ],
            options={
                'verbose_name': 'محجوزة قادمة',
                'verbose_name_plural': '3. المحجوزات (الطلبات من الموقع) 🗓️',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bookings.job',),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='نص الإشعار')),
                ('notif_type', models.CharField(choices=[('standard', '🔔 حجز عادي'), ('voice', '🎙️ رسالة صوتية')], default='standard', max_length=20, verbose_name='نوع التنبيه')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإشعار')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.job', verbose_name='العملية المرتبطة')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': '5. سجل التنبيهات 🔔',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_salary', models.DecimalField(decimal_places=2, default=1000.0, max_digits=8, verbose_name='الراتب اليومي (د.ج)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='العامل')),
            ],
            options={
                'verbose_name': 'راتب عامل',
                'verbose_name_plural': '👤 رواتب العمال اليومية',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('is_present', models.BooleanField(default=False, verbose_name='حاضر؟')),
                ('day_salary_snapshot', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='العامل')),
            ],
            options={
                'verbose_name': 'سجل حضور',
                'verbose_name_plural': '📅 سجل الحضور والغياب',
                'unique_together': {('worker', 'date')},
            },
        ),
    ]
