# Generated by Django 5.2.8 on 2025-12-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='system_mode',
            field=models.CharField(default='commission', editable=False, max_length=20, verbose_name='نظام العملية'),
        ),
    ]
